/**
 * Billing Profiles
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.swisscom.api.sdk.billingprofiles.api;

import com.swisscom.api.sdk.billingprofiles.ApiException;
import com.swisscom.api.sdk.billingprofiles.model.BillingProfilesCollection;
import com.swisscom.api.sdk.billingprofiles.model.Error;
import java.math.BigDecimal;
import com.swisscom.api.sdk.billingprofiles.model.BillingProfileDetails;
import com.swisscom.api.sdk.billingprofiles.model.BillingProfileEligibility;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * #### Search Billing Profiles #### Searches for billing profiles owned by the Swisscom customer identifier provided or contained in access token. At present, only searching for a customer&#39;s best billing profile to be used for payment is supported. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void gETBillingprofilesTest() throws ApiException {
        Boolean bestForPayment = null;
        String sCSVersion = null;
        BigDecimal customerId = null;
        String sCSRequestID = null;
        // BillingProfilesCollection response = api.gETBillingprofiles(bestForPayment, sCSVersion, customerId, sCSRequestID);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * #### Returns Billing Profile Information #### Allows to retrieve the details of the billing profile represented by the billing profile identifier provided as parameter. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void gETBillingprofilesBillingProfileIdTest() throws ApiException {
        String billingProfileId = null;
        String sCSVersion = null;
        String sCSRequestID = null;
        // BillingProfileDetails response = api.gETBillingprofilesBillingProfileId(billingProfileId, sCSVersion, sCSRequestID);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * #### Returns Billing Profile Eligibility #### This API provides the capability to verify the eligibility of a billing profile.  Before submitting the payment transactions using the Payments API, an API-Consumer can check if a specific billing profile is eligible  for making the payment transactions.  The eligibility is determined by considering various factors. Some of the reasons for the billing profile to be non-eligible are * credit has been reached * has been barred * has no paid invoices * does not have any active subscriptions * is not found in the Swisscom billing systems * is not active  This API additionally provides the capability to execute specific eligibility checks.  If only some certain eligiblity checks shall be executed, then a list of desired eligibility checks has to be provided.   If no specific eligibility checks are provided by the API-consumer, then some default checks are executed, depending to  the specific configuration of each API-Consumer.  
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void gETBillingprofilesBillingProfileIdEligibilityTest() throws ApiException {
        String billingProfileId = null;
        String sCSVersion = null;
        BigDecimal customerId = null;
        String sCSRequestID = null;
        // BillingProfileEligibility response = api.gETBillingprofilesBillingProfileIdEligibility(billingProfileId, sCSVersion, customerId, sCSRequestID);

        // TODO: test validations
    }
    
}
